variables:
  #此处对git的子模块进行递归更新
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  # - package

build_job:
  stage: build
  script:
    - echo %PATH%
    - echo %APP_ENV% 
    - call %APP_ENV%\startup_app.bat
    - echo %PATH%
    - python.exe build_target.py
#    - python.exe package_target.py
  tags:
    - win_qt_env
  # artifacts:
  #   name: sdks
  #   expire_in: 1 day
  #   paths:
  #    - sdks

